# -*- coding: utf-8 -*-
from .types import (
    HistoryBar,
    BOLLResult,
    KDJResult,
    MACDResult,
    NewsItem,
    RSIResult,
    ReportData,
    StrategyPerformance,
    TradeLifecycle,
    TradeLifecycleEvent,
    TradePlan,
    RiskSignal,
    StockData,
    StockHistory,
    TechnicalAnalysis,
    TechnicalSignal,
    TrendSummary,
)
from .data_source import DataSource, DataSourceFactory, DataSourceError, FetchResult
from .detector import detect, detect_anomalies, DetectorThresholds
from .quality import assess_quote_quality, normalize_quote_data
from .analysis import (
    analyze_technical_indicators,
    compute_boll,
    compute_kdj,
    compute_macd,
    compute_rsi,
    detect_boll_signals,
    detect_kdj_signals,
    detect_macd_signals,
    detect_rsi_signals,
    technical_risk_signals,
)
from .strategy import SWING_STRATEGY_VERSION, StrategyDecision, evaluate_strategy_action
from .strategy_breakdown import (
    StrategyScorecard,
    StrategySeparation,
    evaluate_strategy_separation,
)
from .mainline_radar import (
    MainlineRadarResult,
    SectorRadarInput,
    evaluate_sector_radar,
    evaluate_sector_rows,
    render_mainline_radar_markdown,
    sector_from_mapping,
)
from .backtest import (
    BacktestConfig,
    BacktestObservation,
    BacktestResult,
    estimate_strategy_performance,
    load_calibration,
    render_backtest_markdown,
    run_swing_backtest,
    save_calibration,
)
from .trade_plan import build_trade_plan, compute_atr, resize_trade_plan
from .lifecycle import (
    LIFECYCLE_SCHEMA_VERSION,
    STATE_CANDIDATE,
    STATE_EXITED,
    STATE_HOLDING,
    STATE_REVIEWED,
    STATE_TRIGGERED,
    find_current_lifecycle,
    lifecycle_from_dict,
    load_lifecycle_ledger,
    plan_fingerprint,
    save_lifecycle_ledger,
    sync_trade_lifecycle,
)
from .market import detect_market, detect_tencent_prefix, detect_sina_prefix, to_eastmoney_secid

__all__ = [
    "NewsItem",
    "HistoryBar",
    "BOLLResult",
    "KDJResult",
    "MACDResult",
    "RSIResult",
    "StockHistory",
    "StockData",
    "RiskSignal",
    "ReportData",
    "StrategyPerformance",
    "TradeLifecycle",
    "TradeLifecycleEvent",
    "TradePlan",
    "TechnicalAnalysis",
    "TechnicalSignal",
    "TrendSummary",
    "DataSource",
    "DataSourceFactory",
    "DataSourceError",
    "FetchResult",
    "detect",
    "detect_anomalies",
    "DetectorThresholds",
    "assess_quote_quality",
    "normalize_quote_data",
    "detect_market",
    "detect_tencent_prefix",
    "detect_sina_prefix",
    "to_eastmoney_secid",
    "analyze_technical_indicators",
    "compute_boll",
    "compute_kdj",
    "compute_macd",
    "compute_rsi",
    "detect_boll_signals",
    "detect_kdj_signals",
    "detect_macd_signals",
    "detect_rsi_signals",
    "technical_risk_signals",
    "StrategyDecision",
    "SWING_STRATEGY_VERSION",
    "evaluate_strategy_action",
    "StrategyScorecard",
    "StrategySeparation",
    "evaluate_strategy_separation",
    "MainlineRadarResult",
    "SectorRadarInput",
    "evaluate_sector_radar",
    "evaluate_sector_rows",
    "render_mainline_radar_markdown",
    "sector_from_mapping",
    "BacktestConfig",
    "BacktestObservation",
    "BacktestResult",
    "estimate_strategy_performance",
    "load_calibration",
    "render_backtest_markdown",
    "run_swing_backtest",
    "save_calibration",
    "build_trade_plan",
    "compute_atr",
    "resize_trade_plan",
    "LIFECYCLE_SCHEMA_VERSION",
    "STATE_CANDIDATE",
    "STATE_TRIGGERED",
    "STATE_HOLDING",
    "STATE_EXITED",
    "STATE_REVIEWED",
    "find_current_lifecycle",
    "lifecycle_from_dict",
    "load_lifecycle_ledger",
    "plan_fingerprint",
    "save_lifecycle_ledger",
    "sync_trade_lifecycle",
]
